### ISSUE TITLE
Cannot create wallet because of -32601: Method not found

### ISSUE THREAD

**Issue by lenhatquang97** [btcsuite/btcwallet#857] opened 2023-04-18 17:40 UTC
Hello everyone, I am testing with case: CreateWallet. What's wrong with this part of code below?
```
func InitializeWallet(opt *Options, seed []byte) error {
	client, err := GetBitcoinRPCClientForWalletCommand(opt, true)
	if err != nil {
		return err
	}

	res, err := client.CreateWallet(opt.Wallet)
	if err != nil {
		return err
	}

	fmt.Print(res.Name)
	return nil
}

func GetBitcoinRPCClientForWalletCommand(opt *Options, create bool) (*rpcclient.Client, error) {
	client, err := GetBitcoinRPCClient(opt)
	if err != nil {
		return nil, err
	}

	if !create {
		result, err := client.LoadWallet(opt.Wallet)
		if err != nil {
			return nil, err
		}
		fmt.Println(result)
	}

	return client, nil
}

func GetBitcoinRPCClient(opt *Options) (*rpcclient.Client, error) {
	certs, err := LoadCerts()
	if err != nil {
		return nil, err
	}

	client, err := rpcclient.New(&rpcclient.ConnConfig{
		Host:         opt.RpcUrl,
		Endpoint:     "ws",
		User:         "4bmeiF7E3ny8cGf8Ok6QJZy/0pk=",
		Pass:         "2oljjSoRFzC5Go7hCGDID6xWi+c=",
		Certificates: certs,
	}, nil)
	if err != nil {
		return nil, err
	}

	return client, nil
}
```

### Main function
```
func main() {
	option := nft.Options{
		ChainArgument:  enum.Chain.Testnet,
		BitcoinDataDir: "./bitcoindatadir/",
		DataDir:        "./datadir/",
		RpcUrl:         "localhost:18332",
		IndexSats:      true,
		Wallet:         "mywalleter",
	}
	err := nft.CreateRun("", &option)
	if err != nil {
		fmt.Println(err)
	}
}
```

Error returns in client.CreateWallet: -32601: Method not found

**Comment by guggero** [comment] 2023-04-20 08:53
It looks like you aren't actually using any code from `btcwallet` but instead `btcd`'s [`rpcclient`](https://github.com/btcsuite/btcd/tree/master/rpcclient) package. The RPC client is just connecting to a node (either `btcd` or `bitcoind`). So the `client.CreateWallet()` method attempts to execute the equivalent of `bitcoin-cli createwallet`. But because you're likely connected to a `btcd` node, that fails because `btcd` itself doesn't have a wallet (see main readme: https://github.com/btcsuite/btcd#btcd).

So maybe it would be better if you stated what you actually want to achieve/implement?

**Comment by lenhatquang97** [comment] 2023-04-20 10:24
Yeah, now I am doing a thesis about a protocol like Ordinals but only with part of embedding data into the transaction. Also, I am planning to do a way of embedding data with using Taro's idea. And I also know that in btcwallet has CreateWallet but it requires database. What kind of database does I need to install?

**Comment by guggero** [comment] 2023-04-20 10:30
`btcwallet` by default uses `bbolt`, which is a built-in file based database. You don't need to explicitly configure anything. But `btcwallet` is more of a library for building your own wallet and not really a fully functional wallet on its own (even though there is a command line aspect to this repo, it doesn't really offer much functionality and AFAIK hasn't been updated in quite a while).

**Comment by guggero** [comment] 2023-04-20 10:47
I'm just saying because `btcwallet` itself isn't a standalone product but a library that is used in other projects, it doesn't contain any example code. Also, the github.com/btcsuite organization is independent from LL, we just use this library in `lnd` as well.

So for what it sounds to me you want to achieve, I'd recommend to use `lnd`'s on-chain wallet functionality and then just use its RPC interface to sign custom transactions.
See the integration test example here that uses `SignOutputRaw`: https://github.com/lightningnetwork/lnd/blob/master/itest/lnd_taproot_test.go#L237

Or this integration test that uses the PSBT RPC interface for creating custom transactions: https://github.com/lightningnetwork/lnd/blob/master/itest/lnd_psbt_test.go#L847

**Comment by guggero** [comment] 2023-04-20 10:50
Also, for troubleshooting questions, I recommend asking in Slack https://lightning.engineering/slack.html.

Closing this issue, since the problem is that the code attempts to connect to a `btcd` node and create a wallet, while a `btcd` node doesn't have that functionality.

**Closed by guggero** 2023-04-20 10:50 UTC

**Comment by lenhatquang97** [comment] 2023-04-20 10:51
Thank you so much for your help! Yeah, I will try using lnd then...
