### ISSUE TITLE
calling wallet.Stop() at application exit results in an error

### ISSUE THREAD

**Issue by manan19** [btcsuite/btcwallet#282] opened 2015-05-15 18:54 UTC
It doesn't happen 100% of the times, so probably a race condition somewhere.

```
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x18 pc=0x43f37b5]

	goroutine 51 [running]:
			github.com/btcsuite/bolt.(*freelist).rollback(0x0, 0x77)
	go/src/github.com/btcsuite/bolt/freelist.go:144 +0x35
			github.com/btcsuite/bolt.(*Tx).rollback(0xc20801ec30)
	go/src/github.com/btcsuite/bolt/tx.go:223 +0x5c
			github.com/btcsuite/bolt.func·010()
	go/src/github.com/btcsuite/bolt/db.go:497 +0x38
			github.com/btcsuite/bolt.(*Tx).write(0xc20801ec30, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/tx.go:428 +0x350
			github.com/btcsuite/bolt.(*Tx).Commit(0xc20801ec30, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/tx.go:176 +0x47c
			github.com/btcsuite/bolt.(*DB).Update(0xc208035380, 0xc2183e1d10, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/db.go:512 +0x169
					github.com/btcsuite/btcwallet/walletdb/bdb.(*namespace).Update(0xc2080c34e0, 0xc2080c33a0, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:348 +0x66
				github.com/btcsuite/btcwallet/waddrmgr.(*Manager).SetSyncedTo(0xc208034680, 0xc2080cc930, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/waddrmgr/sync.go:221 +0x37a
				github.com/btcsuite/btcwallet/wallet.(*Wallet).syncWithChain(0xc2080daa20, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/wallet/wallet.go:433 +0x40f
				github.com/btcsuite/btcwallet/wallet.func·001(0xc2080daa20)
	go/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:32 +0x2b
	created by github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications
	go/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:42 +0x438
```

**Comment by jrick** [comment] 2016-03-09 17:15
This is due to bolt transactions still being active while the database is closed.  I will look into adding a mutex in walletdb to prevent this from happening.

**Comment by jrick** [comment] 2016-03-09 17:19
Actually, this could be a different issue.  The MMIO issues caused by closing the db with active transactions will result in the process segfaulting, but this appears to be a panic from a nil pointer dereference.

**Closed** 2016-03-11 04:08 UTC
