### ISSUE TITLE
Pressing CTRL+C while entering password leaves terminal in no echo state

### ISSUE THREAD

**Issue by ishbir** [btcsuite/btcwallet#296] opened 2015-06-25 08:20 UTC
Steps to reproduce the issue:
- Type in btcwallet --create
- Enter a random password but don't press enter. Press CTRL+C.
- Try typing in anything.
- Tried switching to terminal instead of terminal emulator. No change.

Temporary Fix:
- Reopen terminal emulator.
- Or if used terminal, logout/login.

Permanent Fix:
- Save terminal state as soon as btcwallet starts and reset state in case of interrupt and then shutdown.
```go
// Store terminal state.
state, err := terminal.GetState(int(os.Stdin.Fd()))
if err != nil {
	return err
}

// Restore terminal state in case of interrupt.
addInterruptHandler(func() {
	terminal.Restore(int(os.Stdin.Fd()), state)
})
```
However, things are not as easy as this. Because the interrupt doesn't get propagated i.e. btcwallet doesn't shutdown.

**Comment by jrick** [comment] 2015-06-25 13:53
Thanks for the report.  I was not able to reproduce this in cmd.exe, powershell, and msys2 shells on windows but was able to hit it with xterm and the xfce terminal emulator.  As for resetting, you can just type the command 'reset' (it won't echo, but you can still enter it) and that should reset your terminal back to a usable state without having to reopen it.

**Comment by ishbir** [comment] 2015-06-25 14:02
Oh great, I didn't know about that. I nevertheless think that it's a bug. Any software, if it messes with the terminal's state, should reset it back.

**Comment by jrick** [comment] 2015-06-25 14:12
Yeah I'm playing around with other tools that disable echo and checking how they handle this.  In ssh and sudo's case, the terminal state is always restored.  su eats the SIGINT but if I SIGKILL it the terminal state is also restored.

**Comment by ishbir** [comment] 2015-07-05 07:04
Any updates?

**Comment by dajohi** [comment] 2015-07-05 15:45
@ishbir are you able to test that pull request?

**Comment by ishbir** [comment] 2015-07-06 15:38
Unfortunately, it doesn't work. The problem still persists with Xfce terminal emulator.

**Comment by jrick** [comment] 2016-03-17 05:33
I've been playing around with this for a while (both in btcwallet and in a short program just to test this code) and have been unsuccessful to get the desired behavior.  The "permanent solution" described here (calling `termimal.Restore` with the previous stdin state from before the `terminal.ReadPassword` call) does not work.  I've also tried closing stdin from the interrupt handler at an attempt to force the `ReadPassword` to fail, but it does not exit early with an error.

The best way to exit of these prompts would be to use ^D (EOF) to cause the prompt to error, rather than killing the entire program with ^C.

If you can provide a short example demonstrating the correct behavior (and works on all platforms, `terminal.Terminal` does not work on Windows so we must avoid that), I'd be glad to do a similar implementation in btcwallet.  But given these implementation issues, the poor state of unix terminals and escape codes in general, and the fact that `reset` exists exactly for this issue, I don't think we can devote our time to finding a workaround for this at the moment.

**Closed by jrick** 2016-03-17 05:33 UTC
